### PR TITLE
Labels in config file

### PR DESCRIPTION
**Pull request by jpalider**
Many people seem concerned about magic numbers in configuration file so one commit tries to address the issue but allows to spare a few cycles in another place ;-)
I also added different handling of static strings and removed magic numbers.

### CODE REVIEW

**Comment by jpalider** [comment]
PS Although I tested this against rouge input, please, verify with your setup.

**Comment by jpalider** [comment]
Trying to run for the first time I needed to look up in the code if there are any options available. Hence the idea to show it for anyone trying "-h" - full support  (like -h, --help, etc) would be nice but I'd rather leave it now.

**Comment by jpalider** [comment]
The mcp23008 patch might not be ready for acceptance yet, but it appeared because of two reasons:
1. adding new (external) library into the project (wiringPi) which should be taken into consideration while preparing build environment
2. taking new devices into consideration with regard to any oncoming changes (UI, or whatever)

If you feel like merging it, then great - nothing should be broken but it works as marker in the code, if not - also perfectly fine, I will continue working on this (I hope with humidity sensor added for reference) in a week and/or once I get feedback on what needs reworking.

**Comment by przemyslawzygmunt** [comment]
In the header files created by you change the author name to your name.
 mcp23008.c
 mcp23008.h

In other files - over function names created by you add your name. For example
// Author: Name or nick <email>
void scfg_print_help(const char* app_name)

**Comment by przemyslawzygmunt** [comment]
In case of MCP23008
MCP23008 it shouldn't be defined as channel type.
I think it should be defined as (for example) driver type in config file.

[CHANNEL_01]
driver=mcp23008
mcp_param1=
mcp_param2=

e.t.c.
Do you known what I mean ?

**Comment by przemyslawzygmunt** [comment]
Regarding to MCP23008. You should implement preprocessor condition to allow choice that MCP should be compiled or not. 

#ifdef MCP23008
#endif

**Pull request closed without merging**
